/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import Clases.Medico;
import static Clases.Validaciones.validarEmailFuerte;
import static Clases.Validaciones.verificarCedula;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.StringTokenizer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author UNI
 */
public class AgregarMedico extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarDoctor
     */
    public AgregarMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCedulaMed = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCorreoMed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbEspecialidad = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar Medico");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 0, 12));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel7.setText("Nombres");
        jPanel2.add(jLabel7);

        txtNombre.setDoubleBuffered(true);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre);

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel10.setText("Apellidos");
        jPanel2.add(jLabel10);

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellido);

        jLabel11.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel11.setText("Cédula");
        jPanel2.add(jLabel11);

        txtCedulaMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaMedActionPerformed(evt);
            }
        });
        txtCedulaMed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaMedKeyTyped(evt);
            }
        });
        jPanel2.add(txtCedulaMed);

        jLabel12.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel12.setText("Correo");
        jPanel2.add(jLabel12);

        txtCorreoMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoMedActionPerformed(evt);
            }
        });
        txtCorreoMed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoMedKeyTyped(evt);
            }
        });
        jPanel2.add(txtCorreoMed);

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("Especialidad");
        jPanel2.add(jLabel8);

        cmbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>" }));
        jPanel2.add(cmbEspecialidad);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1435355686_pencil.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1435357592_Timetable.png"))); // NOI18N
        jButton2.setText("Guardar y Agregar Horario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1435355601_sign-error.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 684, 407);
    }// </editor-fold>//GEN-END:initComponents

    public void Guardar(){
        String Nombre = txtNombre.getText().trim();
        String Apellido = txtApellido.getText().trim();
        String Cedula = txtCedulaMed.getText().trim();
        String Correo = txtCorreoMed.getText().trim();
        int cmbEsp = cmbEspecialidad.getSelectedIndex();
        int ID_Especialidad = ID_Esp[cmbEsp];
     /*   String HoraInicio = (String) cmbDesde.getSelectedItem();
        String HoraFinal = (String) cmbHasta.getSelectedItem();
        boolean L = ckL.isSelected();
        boolean M = ckM.isSelected();
        boolean X = ckX.isSelected();
        boolean J = ckJ.isSelected();
        boolean V = ckV.isSelected();
        boolean S = ckS.isSelected();
        boolean D = ckD.isSelected();
        
        int HRi = cmbDesde.getSelectedIndex();
        int HRs = cmbHasta.getSelectedIndex();
        
        if(HRi>HRs){
                    JOptionPane.showMessageDialog
        (this, "La hora de salida no puede ser menor que la de entrada, y la hora de entrada no puede ser mayor que"
                + " la de salida",
                "Seleccione correctamente",JOptionPane.ERROR_MESSAGE);
                    return;
        }
        
             */
         
         
        if("".equals(Nombre)||"".equals(Apellido)|| "".equals(Correo)||"".equals(Cedula)||cmbEsp==0)
                //||"<Seleccione>".equals(HoraFinal)
           //     ||"<Seleccione>".equals(HoraInicio))
            
        {
                    JOptionPane.showMessageDialog
        (this, "Complete todos los campos y seleccione correctamente",
                "Complete",JOptionPane.ERROR_MESSAGE);
        }
       
        if(verificarCedula(Cedula)==false){
         JOptionPane.showMessageDialog
        (this, "La cedula ingresada no es valida",
                "Corrija",JOptionPane.ERROR_MESSAGE);
        }
         if(validarEmailFuerte(Correo)==false){
         JOptionPane.showMessageDialog
        (this, "El correo no cumple con la estructura correcta Ej:graciela.moreno@epn.edu.ec",
                "Corrija",JOptionPane.ERROR_MESSAGE);
        }
        else{
          
            
            Horario H = new Horario(null, true);
            H.setAM(this);
            H.setNombre(Nombre);
            H.setApellido(Apellido);
            H.setCedula(Cedula);
            H.setCorreo(Correo);
            H.setID_Especialidad(ID_Especialidad);
            H.setVisible(true);
            
       //     Limpiar();// TODO add your handling code here:

            }
        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        Guardar(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    ResultSet resultado;
    int ID_Esp [];
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
      
        
     int ID_Especialidad = 0;
     
      try{
         
     resultado = Conexion.consulta("Select Max(ID_Especialidad) from Especialidad");
         
     while(resultado.next()){
         ID_Especialidad = resultado.getInt(1);
     }
     }catch(SQLException ex){
         
     }
        
      
      ID_Especialidad++;
   
      ID_Esp = new int[ID_Especialidad];


       
      ID_Esp [0] = 0; 
      
      int i = 1;
      
      try{
         
     resultado = Conexion.consulta("Select ID_Especialidad, Nombre from Especialidad Where Estado = 1");
         
     while(resultado.next()){
         ID_Esp [i] = resultado.getInt(1);
         cmbEspecialidad.addItem(resultado.getString(2).trim());
         i++;
     }
     }catch(SQLException ex){
         
     }
       
        

// TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    
    
    public void Limpiar(){
        txtApellido.setText("");
        txtNombre.setText("");
        txtCedulaMed.setText("");
        txtCorreoMed.setText("");
//        cmbDesde.setSelectedIndex(0);
        cmbEspecialidad.setSelectedIndex(0);
  /*     cmbHasta.setSelectedIndex(0);
        ckD.setSelected(false);
        ckJ.setSelected(false);
        ckL.setSelected(false);
        ckM.setSelected(false);
        ckS.setSelected(false);
        ckV.setSelected(false);
        ckX.setSelected(false);*/
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
char a = evt.getKeyChar();

if(!Character.isLetter(a)&&!Character.isISOControl(a)&&a!=' '){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
}        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
char a = evt.getKeyChar();

if(!Character.isLetter(a)&&!Character.isISOControl(a)&&a!=' '){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
}        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCedulaMedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaMedKeyTyped
      char a = evt.getKeyChar();
      
        if (txtCedulaMed.getText().length()>=10){
             evt.consume();
    Toolkit.getDefaultToolkit().beep();
        }

if(!Character.isDigit(a) ){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
}        
    }//GEN-LAST:event_txtCedulaMedKeyTyped

    private void txtCedulaMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaMedActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaMedActionPerformed

    private void txtCorreoMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMedActionPerformed

    private void txtCorreoMedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoMedKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMedKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbEspecialidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedulaMed;
    private javax.swing.JTextField txtCorreoMed;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
